name: "sccache action - speedup Rust GitHub actions"
description: "A GitHub Action that speeds up Rust compilation with sccache."
inputs:
  cache-key:
    description: "The cache key prefix, on which partial matches are made"
    default: "sccache"
  cache-suffix:
    description: "The cache key suffix, which can make keys unique (e.g. hash of lock file)"
    default: ""
  cache-date:
    description: "Whether to append a datetime string to the cache to make it unique"
    default: true
  cache-save:
    description: "A Flag that indicates whether or not saving the cache"
    default: true
  cache-update:
    description: "A Flag that indicates whether or not updating cache when hit"
    default: true
  release-name:
    description: "The sccache version. e.g. v0.3.0"
    default: "latest"
  arch:
    description: "The sccache binary architecture."
    default: ""
runs:
  using: "node16"
  main: "dist/main/index.js"
  post: "dist/post/index.js"
branding:
  icon: "archive"
  color: "black"
